jQuery.sap.declare("com.ril.PRMS.util.mandit");
com.ril.PRMS.util.mandit = {
		applyMandit:function(view){
			sap.ui.getCore().byId(view+"--"+"cmbOwnrTyp").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbRelationType").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbRelationSubType").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"DtpckScurtyStrtDte").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"DtpckScurtyEndDte").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptSecrtyAmnt").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"multicbxPrdctGroup").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"mltcombxAssgndBussGroup").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptAccountHldrName").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inputAccountNo").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptBankName").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptIfcCode").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptBranchName").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptExtrnlID").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptPRMID").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptCompName").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptAliasName").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbLocationType").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbLocationSubType").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptCompEmail").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptmobileNo").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbStrtWkngDay").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbEndWkngDay").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptHouseno").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptPostalCde").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptAddrCityId").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptCity").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbCountry").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbR4GState").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbCircle").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbDelvryCntr").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbSurtyType").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptScurtyInstrmntDtls").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbJobFnctn").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"inptjobDescr").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbSaluton").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"cmbGender").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"fname").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"lName").setValueState("Warning");
			sap.ui.getCore().byId(view+"--"+"datePickrbirthday").setValueState("Warning");
//			sap.ui.getCore().byId(view+"--"+"cmbGender").setValueState("Warning");
//			sap.ui.getCore().byId(view+"--"+"cmbGender").setValueState("Warning");
//			sap.ui.getCore().byId(view+"--"+"cmbGender").setValueState("Warning");
//			sap.ui.getCore().byId(view+"--"+"cmbGender").setValueState("Warning");
		}
};